@echo off
echo Installing Tailwind CSS and dependencies...
call npm install tailwindcss postcss autoprefixer
echo Initializing Tailwind configuration...
call npx tailwindcss init -p
echo Starting development server...
call npm run dev 